version: '2'
services:
  pigeon-gateway:
    build:
      context: ./pigeon-gateway
    restart: always
    ports:
      - 1140:1140
    container_name: pigeon-gateway
    hostname: pigeon-gateway

  pigeon-rbac:
    build:
      context: ./pigeon-rbac/rbac-biz
    restart: always
    ports:
      - 1141:1141
    container_name: pigeon-rbac
    hostname: pigeon-rbac


  pigeon-auth:
    build:
      context: ./pigeon-auth
    restart: always
    ports:
      - 1142:1142
    container_name: pigeon-auth
    hostname: pigeon-auth

#  pigeon-demo:
#    build:
#      context: ./pigeon-demo/demo-biz
#    restart: always
#    ports:
#      - 1150:1150
#    container_name: pigeon-demo
#    hostname: pigeon-demo

  pigeon-openapi:
    build:
      context: ./pigeon-openapi
    restart: always
    ports:
      - 1143:1143
    container_name: pigeon-openapi
    hostname: pigeon-openapi

  pigeon-file:
    build:
      context: ./pigeon-file/file-biz
    restart: always
    ports:
      - 1144:1144
    container_name: pigeon-file
    hostname: pigeon-file