version: '3'
services:
  pigeon-gateway:
    build:
      context: ./pigeon-gateway
    restart: always
    ports:
      - 1140:1140
    container_name: pigeon-gateway
    hostname: pigeon-gateway
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 128M

  pigeon-rbac:
    build:
      context: ./pigeon-rbac/rbac-biz
    restart: always
    ports:
      - 1141:1141
    container_name: pigeon-rbac
    hostname: pigeon-rbac
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 128M

  pigeon-auth:
    build:
      context: ./pigeon-auth
    restart: always
    ports:
      - 1142:1142
    container_name: pigeon-auth
    hostname: pigeon-auth
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 128M

#  pigeon-demo:
#    build:
#      context: ./pigeon-demo/demo-biz
#    restart: always
#    ports:
#      - 1150:1150
#    container_name: pigeon-demo
#    hostname: pigeon-demo

  pigeon-openapi:
    build:
      context: ./pigeon-openapi
    restart: always
    ports:
      - 1143:1143
    container_name: pigeon-openapi
    hostname: pigeon-openapi
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 128M

  pigeon-file:
    build:
      context: ./pigeon-file/file-biz
    restart: always
    ports:
      - 1144:1144
    container_name: pigeon-file
    hostname: pigeon-file
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 128M

  pigeon-admin:
    build:
      context: ./pigeon-governance/pigeon-admin
    restart: always
    ports:
      - 1151:1151
    container_name: pigeon-admin
    hostname: pigeon-admin
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 128M